# Version de docker-compose
version: '3.9'

# Définit service / conteneur que D-C doit gerer
services:
   
  # Nom du service
  app: 
    image: todolistflask
    build:
      # Repertoire a utiliser pour build
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000

    # Pour persister les données
    volumes:
      - todolist.db:/app/db
volumes:
  todolist.db:
