name: Docker Image CI test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to docker-hub
      run:  docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build docker-image
      run: docker build -t chicchino/todolist-flask:latest .
    
    - name: Tag docker-image
      run: docker tag $(docker images -aq | head -n1) ${{ secrets.DOCKER_USERNAME }}/todolist-flask:latest
      
    - name: Push to registry
      run: docker push chicchino/todolist-flask:latest
    
